class Constants {
  static const Map<String, List<Map<String, dynamic>>> allTypes = {
    "General Science (I-III)": [
      {
        'id': 'living',
        'title': "Living vs Non-living things",
        'tier': 'free',
        'topics': [
          'Characteristics of living things',
          'Differences between living and non-living',
          'Basic needs of living organisms',
          'Examples from daily life',
        ],
      },
      {
        'id': 'plants',
        'title': "Plants and Animals",
        'tier': 'free',
        'topics': [
          'Types of plants and their parts',
          'Common animals and their habitats',
          'Pet animals vs wild animals',
          'Plant and animal interdependence',
        ],
      },
      {
        'id': 'body',
        'title': "Human Body Basics",
        'tier': 'free',
        'topics': [
          'Major body parts and their functions',
          'Five senses and their organs',
          'Basic hygiene practices',
          'Simple body functions',
        ],
      },
      {
        'id': 'food',
        'title': "Food & Nutrition (Basic)",
        'tier': 'free',
        'topics': [
          'Basic food groups',
          'Healthy eating habits',
          'Importance of balanced diet',
          'Food sources and nutrition',
        ],
      },
      {
        'id': 'water',
        'title': "Water, Air, Weather",
        'tier': 'free',
        'topics': [
          'Properties of air and water',
          'Weather patterns and changes',
          'Importance of clean air and water',
          'Basic weather observations',
        ],
      },
      {
        'id': 'sky',
        'title': "Day & Night, Sun, Moon, Earth",
        'tier': 'free',
        'topics': [
          'Day and night cycle',
          'Sun as source of light and heat',
          'Moon phases basics',
          'Earth\'s basic features',
        ],
      },
      {
        'id': 'surroundings',
        'title': "Our Surroundings",
        'tier': 'free',
        'topics': [
          'Home and school environment',
          'Natural and man-made surroundings',
          'Community spaces',
          'Environmental awareness',
        ],
      },
      {
        'id': 'safety',
        'title': "Safety and Hygiene",
        'tier': 'free',
        'topics': [
          'Personal safety rules',
          'Hygiene practices',
          'Emergency contacts',
          'Safe behavior at home and school',
        ],
      },
    ],
    "Environmental Awareness (I-III)": [
      {
        'id': 'seasons',
        'title': "Seasons",
        'tier': 'free',
        'topics': [
          'Characteristics of different seasons',
          'Seasonal changes in nature',
          'Clothing and activities for seasons',
          'Weather patterns across seasons',
        ],
      },
      {
        'id': 'transport',
        'title': "Transport",
        'tier': 'free',
        'topics': [
          'Modes of transportation',
          'Land, water, and air transport',
          'Safety in transportation',
          'Importance of transport',
        ],
      },
      {
        'id': 'helpers',
        'title': "Community Helpers",
        'tier': 'free',
        'topics': [
          'Different community helpers',
          'Roles and responsibilities',
          'Tools used by helpers',
          'Respecting community workers',
        ],
      },
      {
        'id': 'habits',
        'title': "Good Habits",
        'tier': 'free',
        'topics': [
          'Daily routine habits',
          'Personal cleanliness',
          'Good manners and behavior',
          'Health maintenance practices',
        ],
      },
      {
        'id': 'houses',
        'title': "Types of Houses",
        'tier': 'free',
        'topics': [
          'Different types of houses',
          'Building materials',
          'Household facilities',
          'Clean and healthy homes',
        ],
      },
    ],
    "Environmental Science (IV-V)": [
      {
        'id': 'plants',
        'title': "Plant Life",
        'tier': 'free',
        'topics': [
          'Plant parts and functions',
          'Photosynthesis process',
          'Plant growth requirements',
          'Types of plants and their uses',
        ],
      },
      {
        'id': 'animals',
        'title': "Animal Life",
        'tier': 'free',
        'topics': [
          'Animal adaptations',
          'Reproduction in animals',
          'Animal habitats',
          'Food chains and webs',
        ],
      },
      {
        'id': 'human',
        'title': "Human Body Systems",
        'tier': 'free',
        'topics': [
          'Major organ systems',
          'Digestive system process',
          'Respiratory system',
          'Circulatory system basics',
        ],
      },
      {
        'id': 'soil',
        'title': "Soil",
        'tier': 'free',
        'topics': [
          'Soil formation process',
          'Types of soil',
          'Soil composition',
          'Soil conservation methods',
        ],
      },
      {
        'id': 'watercycle',
        'title': "Water Cycle",
        'tier': 'free',
        'topics': [
          'Evaporation, condensation, precipitation',
          'Water distribution on Earth',
          'Importance of water cycle',
          'Conservation of water',
        ],
      },
      {
        'id': 'rocks',
        'title': "Rocks & Minerals",
        'tier': 'free',
        'topics': [
          'Types of rocks',
          'Rock formation processes',
          'Mineral identification',
          'Uses of rocks and minerals',
        ],
      },
      {
        'id': 'resources',
        'title': "Natural Resources",
        'tier': 'free',
        'topics': [
          'Renewable and non-renewable resources',
          'Conservation practices',
          'Sustainable resource use',
          'Environmental protection',
        ],
      },
      {
        'id': 'pollution',
        'title': "Pollution",
        'tier': 'free',
        'topics': [
          'Types of pollution',
          'Pollution causes and effects',
          'Pollution prevention',
          'Environmental cleanliness',
        ],
      },
      {
        'id': 'machines',
        'title': "Simple Machines",
        'tier': 'free',
        'topics': [
          'Types of simple machines',
          'Mechanical advantage',
          'Everyday applications',
          'Energy transfer principles',
        ],
      },
    ],
    "Basic Physics (IV-V)": [
      {
        'id': 'force',
        'title': "Force and Motion",
        'tier': 'free',
        'topics': [
          'Types of forces',
          'Effects of force on motion',
          'Gravitational force',
          'Frictional force basics',
        ],
      },
      {
        'id': 'light',
        'title': "Light and Shadows",
        'tier': 'free',
        'topics': [
          'Properties of light',
          'Shadow formation',
          'Reflection basics',
          'Light and vision',
        ],
      },
      {
        'id': 'electricity',
        'title': "Electricity Basics",
        'tier': 'free',
        'topics': [
          'Basic electrical concepts',
          'Simple circuits',
          'Conductors and insulators',
          'Electrical safety',
        ],
      },
    ],
    "Basic Chemistry (IV-V)": [
      {
        'id': 'matter',
        'title': "States of Matter",
        'tier': 'free',
        'topics': [
          'Solid, liquid, gas properties',
          'State changes',
          'Particle theory basics',
          'Examples of each state',
        ],
      },
      {
        'id': 'airwater',
        'title': "Air & Water Composition",
        'tier': 'free',
        'topics': [
          'Composition of air',
          'Properties of water',
          'Water purification',
          'Air and water pollution',
        ],
      },
      {
        'id': 'separation',
        'title': "Separation of Substances",
        'tier': 'free',
        'topics': [
          'Methods of separation',
          'Filtration process',
          'Evaporation technique',
          'Decantation method',
        ],
      },
    ],
    "Physics (VI)": [
      {
        'id': 'motion',
        'title': "Motion",
        'tier': 'free',
        'topics': [
          'Types of motion',
          'Speed and velocity basics',
          'Distance and displacement',
          'Measurement of motion',
        ],
      },
      {
        'id': 'light',
        'title': "Light & Shadows",
        'tier': 'free',
        'topics': [
          'Rectilinear propagation of light',
          'Formation of shadows',
          'Reflection of light',
          'Pinhole camera principle',
        ],
      },
      {
        'id': 'electricity',
        'title': "Electricity & Circuits",
        'tier': 'free',
        'topics': [
          'Electric current basics',
          'Simple circuit components',
          'Conductors and insulators',
          'Circuit diagrams',
        ],
      },
      {
        'id': 'magnets',
        'title': "Magnets",
        'tier': 'free',
        'topics': [
          'Magnetic properties',
          'Poles of magnets',
          'Magnetic field basics',
          'Uses of magnets',
        ],
      },
    ],
    "Chemistry (VI)": [
      {
        'id': 'matter',
        'title': "Matter & Its Nature",
        'tier': 'free',
        'topics': [
          'Classification of matter',
          'Elements and compounds',
          'Physical properties',
          'States of matter',
        ],
      },
      {
        'id': 'separation',
        'title': "Separation Methods",
        'tier': 'free',
        'topics': [
          'Hand-picking method',
          'Sieving technique',
          'Filtration process',
          'Evaporation method',
        ],
      },
      {
        'id': 'changes',
        'title': "Changes Around Us",
        'tier': 'free',
        'topics': [
          'Physical changes examples',
          'Chemical changes identification',
          'Reversible changes',
          'Irreversible changes',
        ],
      },
    ],
    "Biology (VI)": [
      {
        'id': 'food',
        'title': "Food & Digestion",
        'tier': 'free',
        'topics': [
          'Components of food',
          'Digestive process',
          'Balanced diet requirements',
          'Nutritional deficiencies',
        ],
      },
      {
        'id': 'organisms',
        'title': "Living Organisms",
        'tier': 'free',
        'topics': [
          'Characteristics of living organisms',
          'Habitat and adaptation',
          'Classification basics',
          'Biodiversity introduction',
        ],
      },
      {
        'id': 'materials',
        'title': "Sorting Materials",
        'tier': 'free',
        'topics': [
          'Grouping materials',
          'Properties based classification',
          'Natural and synthetic materials',
          'Uses of different materials',
        ],
      },
      {
        'id': 'movement',
        'title': "Body Movements",
        'tier': 'free',
        'topics': [
          'Human skeletal system',
          'Joints and their types',
          'Muscular movement',
          'Animal movement patterns',
        ],
      },
    ],
    "Physics (VII)": [
      {
        'id': 'heat',
        'title': "Heat",
        'tier': 'free',
        'topics': [
          'Heat transfer methods',
          'Temperature measurement',
          'Thermal expansion',
          'Heat conductors and insulators',
        ],
      },
      {
        'id': 'motion',
        'title': "Motion & Time",
        'tier': 'free',
        'topics': [
          'Uniform and non-uniform motion',
          'Speed calculation',
          'Time measurement',
          'Distance-time graphs',
        ],
      },
      {
        'id': 'current',
        'title': "Electric Current",
        'tier': 'free',
        'topics': [
          'Electric current concepts',
          'Circuit components',
          'Heating effect of current',
          'Magnetic effect of current',
        ],
      },
      {
        'id': 'light',
        'title': "Light",
        'tier': 'free',
        'topics': [
          'Reflection of light',
          'Spherical mirrors',
          'Image formation',
          'Dispersion of light',
        ],
      },
    ],
    "Chemistry (VII)": [
      {
        'id': 'acids',
        'title': "Acids, Bases, Salts",
        'tier': 'free',
        'topics': [
          'Properties of acids and bases',
          'Indicators and pH',
          'Neutralization reactions',
          'Uses of salts',
        ],
      },
      {
        'id': 'changes',
        'title': "Physical & Chemical Changes",
        'tier': 'free',
        'topics': [
          'Physical change characteristics',
          'Chemical change identification',
          'Rusting and corrosion',
          'Crystallization process',
        ],
      },
      {
        'id': 'fiber',
        'title': "Fiber to Fabric",
        'tier': 'free',
        'topics': [
          'Natural fibers sources',
          'Synthetic fibers production',
          'Fabric manufacturing',
          'Properties of different fibers',
        ],
      },
      {
        'id': 'water',
        'title': "Water, Weather, Climate",
        'tier': 'free',
        'topics': [
          'Water conservation methods',
          'Weather and climate differences',
          'Animal adaptations to climate',
          'Water cycle processes',
        ],
      },
    ],
    "Biology (VII)": [
      {
        'id': 'nutrition',
        'title': "Nutrition",
        'tier': 'free',
        'topics': [
          'Nutrition in plants',
          'Nutrition in animals',
          'Photosynthesis process',
          'Human digestive system',
        ],
      },
      {
        'id': 'respiration',
        'title': "Respiration",
        'tier': 'free',
        'topics': [
          'Aerobic respiration',
          'Anaerobic respiration',
          'Breathing mechanism',
          'Gas exchange in plants',
        ],
      },
      {
        'id': 'transport',
        'title': "Transportation in Animals & Plants",
        'tier': 'free',
        'topics': [
          'Circulatory system in humans',
          'Transport in plants',
          'Blood components',
          'Transpiration process',
        ],
      },
      {
        'id': 'reproduction',
        'title': "Reproduction",
        'tier': 'free',
        'topics': [
          'Asexual reproduction',
          'Sexual reproduction in plants',
          'Pollination methods',
          'Seed dispersal mechanisms',
        ],
      },
      {
        'id': 'waste',
        'title': "Waste Management",
        'tier': 'free',
        'topics': [
          'Sewage treatment',
          'Water purification',
          'Waste management',
          'Sanitation practices',
        ],
      },
    ],
    "Physics (VIII)": [
      {
        'id': 'force',
        'title': "Force & Pressure",
        'tier': 'free',
        'topics': [
          'Contact and non-contact forces',
          'Pressure calculation',
          'Atmospheric pressure',
          'Liquid pressure',
        ],
      },
      {
        'id': 'friction',
        'title': "Friction",
        'tier': 'free',
        'topics': [
          'Types of friction',
          'Factors affecting friction',
          'Advantages and disadvantages',
          'Reducing friction methods',
        ],
      },
      {
        'id': 'sound',
        'title': "Sound",
        'tier': 'free',
        'topics': [
          'Sound production and propagation',
          'Characteristics of sound',
          'Reflection of sound',
          'Human ear structure',
        ],
      },
      {
        'id': 'chemical',
        'title': "Chemical Effects of Current",
        'tier': 'free',
        'topics': [
          'Electroplating process',
          'Chemical effects of current',
          'Electrolysis basics',
          'Applications in industry',
        ],
      },
      {
        'id': 'light',
        'title': "Light",
        'tier': 'free',
        'topics': [
          'Multiple reflection',
          'Regular and diffuse reflection',
          'Human eye structure',
          'Care of eyes',
        ],
      },
    ],

    //Continue from here
    "Chemistry (VIII)": [
      {
        'id': 'fibers',
        'title': "Synthetic Fibers",
        'tier': 'free',
        'topics': [
          'Types of synthetic fibers',
          'Plastics classification',
          'Polymerization basics',
          'Environmental impact',
        ],
      },
      {
        'id': 'metals',
        'title': "Metals & Non-metals",
        'tier': 'free',
        'topics': [
          'Physical properties of metals',
          'Chemical properties of metals',
          'Reactivity series',
          'Uses of metals and non-metals',
        ],
      },
      {
        'id': 'coal',
        'title': "Coal & Petroleum",
        'tier': 'free',
        'topics': [
          'Formation of coal',
          'Petroleum refining',
          'Natural gas uses',
          'Conservation of resources',
        ],
      },
      {
        'id': 'combustion',
        'title': "Combustion & Flame",
        'tier': 'free',
        'topics': [
          'Combustion process',
          'Types of combustion',
          'Flame structure',
          'Fuel efficiency',
        ],
      },
    ],
    "Biology (VIII)": [
      {
        'id': 'micro',
        'title': "Microorganisms",
        'tier': 'free',
        'topics': [
          'Beneficial microorganisms',
          'Harmful microorganisms',
          'Food preservation',
          'Vaccines and antibiotics',
        ],
      },
      {
        'id': 'puberty',
        'title': "Reaching Puberty",
        'tier': 'free',
        'topics': [
          'Adolescence changes',
          'Hormonal control',
          'Reproductive health',
          'Personal hygiene',
        ],
      },
      {
        'id': 'conservation',
        'title': "Conservation of Plants & Animals",
        'tier': 'free',
        'topics': [
          'Biodiversity importance',
          'Protected areas',
          'Endangered species',
          'Reforestation methods',
        ],
      },
      {
        'id': 'diseases',
        'title': "Diseases",
        'tier': 'free',
        'topics': [
          'Infectious diseases',
          'Non-infectious diseases',
          'Disease prevention',
          'Immune system basics',
        ],
      },
      {
        'id': 'reproduction',
        'title': "Reproduction in Animals",
        'tier': 'free',
        'topics': [
          'Sexual reproduction',
          'Asexual reproduction',
          'Reproductive systems',
          'Embryo development',
        ],
      },
    ],
    "Physics (IX)": [
      {
        'id': 'motion',
        'title': "Motion",
        'tier': 'free',
        'topics': [
          'Distance and displacement',
          'Uniform and accelerated motion',
          'Equations of motion',
          'Graphical representation',
        ],
      },
      {
        'id': 'force',
        'title': "Force & Laws",
        'tier': 'free',
        'topics': [
          'Newton\'s laws of motion',
          'Inertia and momentum',
          'Conservation of momentum',
          'Force and acceleration',
        ],
      },
      {
        'id': 'gravity',
        'title': "Gravitation",
        'tier': 'free',
        'topics': [
          'Universal law of gravitation',
          'Free fall acceleration',
          'Mass and weight',
          'Planetary motion',
        ],
      },
      {
        'id': 'work',
        'title': "Work & Energy",
        'tier': 'free',
        'topics': [
          'Work and energy relationship',
          'Kinetic and potential energy',
          'Power calculation',
          'Energy conservation',
        ],
      },
      {
        'id': 'sound',
        'title': "Sound",
        'tier': 'free',
        'topics': [
          'Sound wave properties',
          'Reflection and echo',
          'Ultrasound applications',
          'Human voice production',
        ],
      },
    ],
    "Chemistry (IX)": [
      {
        'id': 'matter',
        'title': "Matter",
        'tier': 'free',
        'topics': [
          'Physical nature of matter',
          'States of matter interconversion',
          'Evaporation and boiling',
          'Latent heat concepts',
        ],
      },
      {
        'id': 'atoms',
        'title': "Atoms & Molecules",
        'tier': 'free',
        'topics': [
          'Laws of chemical combination',
          'Atomic and molecular masses',
          'Mole concept introduction',
          'Formula calculations',
        ],
      },
      {
        'id': 'structure',
        'title': "Structure of Atom",
        'tier': 'free',
        'topics': [
          'Atomic models development',
          'Electron distribution',
          'Valency concept',
          'Isotopes and isobars',
        ],
      },
      {
        'id': 'laws',
        'title': "Fundamental Chemical Laws",
        'tier': 'free',
        'topics': [
          'Law of conservation of mass',
          'Law of constant proportions',
          'Law of multiple proportions',
          'Gay-Lussac\'s law',
        ],
      },
    ],
    "Biology (IX)": [
      {
        'id': 'cell',
        'title': "Cell",
        'tier': 'free',
        'topics': [
          'Cell structure and organelles',
          'Prokaryotic vs eukaryotic cells',
          'Cell division basics',
          'Cell functions',
        ],
      },
      {
        'id': 'tissues',
        'title': "Tissues",
        'tier': 'free',
        'topics': [
          'Plant tissues types',
          'Animal tissues classification',
          'Tissue functions',
          'Meristematic tissues',
        ],
      },
      {
        'id': 'diversity',
        'title': "Diversity in Living Organisms",
        'tier': 'free',
        'topics': [
          'Classification systems',
          'Five kingdom classification',
          'Binomial nomenclature',
          'Species concept',
        ],
      },
      {
        'id': 'health',
        'title': "Health & Diseases",
        'tier': 'free',
        'topics': [
          'Infectious diseases',
          'Non-infectious diseases',
          'Immunity types',
          'Health and hygiene',
        ],
      },
    ],
    "Physics (X)": [
      {
        'id': 'light',
        'title': "Light (Reflection, Refraction)",
        'tier': 'free',
        'topics': [
          'Laws of reflection',
          'Spherical mirrors',
          'Refraction through lenses',
          'Lens formula applications',
        ],
      },
      {
        'id': 'eye',
        'title': "Human Eye",
        'tier': 'free',
        'topics': [
          'Eye structure and function',
          'Defects of vision',
          'Dispersion of light',
          'Atmospheric refraction',
        ],
      },
      {
        'id': 'electricity',
        'title': "Electricity",
        'tier': 'free',
        'topics': [
          'Ohm\'s law applications',
          'Series and parallel circuits',
          'Electrical power calculation',
          'Heating effect of current',
        ],
      },
      {
        'id': 'magnetic',
        'title': "Magnetic Effects of Current",
        'tier': 'free',
        'topics': [
          'Magnetic field due to current',
          'Electromagnetic induction',
          'Electric motor principle',
          'Electric generator working',
        ],
      },
      {
        'id': 'energy',
        'title': "Energy Sources",
        'tier': 'free',
        'topics': [
          'Conventional energy sources',
          'Non-conventional energy',
          'Solar energy applications',
          'Environmental aspects',
        ],
      },
    ],
    "Chemistry (X)": [
      {
        'id': 'reactions',
        'title': "Chemical Reactions",
        'tier': 'free',
        'topics': [
          'Chemical equation balancing',
          'Types of chemical reactions',
          'Oxidation-reduction',
          'Corrosion and rancidity',
        ],
      },
      {
        'id': 'acids',
        'title': "Acids/Bases/Salts",
        'tier': 'free',
        'topics': [
          'pH scale importance',
          'Preparation and uses',
          'Neutralization in daily life',
          'Indicators and their uses',
        ],
      },
      {
        'id': 'metals',
        'title': "Metals & Non-metals",
        'tier': 'free',
        'topics': [
          'Reactivity series applications',
          'Extraction of metals',
          'Corrosion prevention',
          'Alloys formation',
        ],
      },
      {
        'id': 'carbon',
        'title': "Carbon Compounds",
        'tier': 'free',
        'topics': [
          'Versatile nature of carbon',
          'Homologous series',
          'Nomenclature of compounds',
          'Functional groups',
        ],
      },
      {
        'id': 'periodic',
        'title': "Periodic Classification",
        'tier': 'free',
        'topics': [
          'Modern periodic law',
          'Periodic trends',
          'Periodic properties',
          'Element classification',
        ],
      },
    ],
    "Biology (X)": [
      {
        'id': 'life',
        'title': "Life Processes",
        'tier': 'free',
        'topics': [
          'Nutrition processes',
          'Respiration mechanisms',
          'Transportation systems',
          'Excretion processes',
        ],
      },
      {
        'id': 'control',
        'title': "Control & Coordination",
        'tier': 'free',
        'topics': [
          'Nervous system coordination',
          'Endocrine system functions',
          'Plant hormones',
          'Reflex actions',
        ],
      },
      {
        'id': 'reproduction',
        'title': "Reproduction",
        'tier': 'free',
        'topics': [
          'Asexual reproduction methods',
          'Sexual reproduction in plants',
          'Human reproductive system',
          'Reproductive health',
        ],
      },
      {
        'id': 'heredity',
        'title': "Heredity & Evolution",
        'tier': 'free',
        'topics': [
          'Mendel\'s laws of inheritance',
          'Sex determination',
          'Evolution evidence',
          'Natural selection',
        ],
      },
      {
        'id': 'environment',
        'title': "Environment",
        'tier': 'free',
        'topics': [
          'Ecosystem components',
          'Food chains and webs',
          'Environmental problems',
          'Conservation methods',
        ],
      },
    ],
    "Physics (XI)": [
      {
        'id': 'units',
        'title': "Units & Measurements",
        'tier': 'free',
        'topics': [
          'Fundamental and derived units',
          'Dimensional analysis',
          'Measurement techniques',
          'Significant figures',
        ],
      },
      {
        'id': 'kinematics',
        'title': "Kinematics",
        'tier': 'free',
        'topics': [
          'Motion in straight line',
          'Motion in plane',
          'Relative velocity',
          'Projectile motion',
        ],
      },
      {
        'id': 'laws',
        'title': "Laws of Motion",
        'tier': 'free',
        'topics': [
          'Newton\'s laws applications',
          'Friction concepts',
          'Circular motion dynamics',
          'Solving motion problems',
        ],
      },
      {
        'id': 'work',
        'title': "Work, Energy, Power",
        'tier': 'free',
        'topics': [
          'Work-energy theorem',
          'Conservative forces',
          'Power and efficiency',
          'Collision theory',
        ],
      },
      {
        'id': 'thermo',
        'title': "Thermodynamics",
        'tier': 'free',
        'topics': [
          'Thermal properties',
          'Heat transfer mechanisms',
          'Thermodynamic processes',
          'Heat engine efficiency',
        ],
      },
      {
        'id': 'oscillations',
        'title': "Oscillations",
        'tier': 'free',
        'topics': [
          'Simple harmonic motion',
          'Wave characteristics',
          'Sound wave properties',
          'Doppler effect',
        ],
      },
      {
        'id': 'gravitation',
        'title': "Gravitation",
        'tier': 'free',
        'topics': [
          'Kepler\'s laws',
          'Gravitational field',
          'Satellite motion',
          'Gravitational potential',
        ],
      },
      {
        'id': 'properties',
        'title': "Mechanical Properties",
        'tier': 'free',
        'topics': [
          'Elastic behavior',
          'Fluid mechanics',
          'Surface tension',
          'Viscosity concepts',
        ],
      },
    ],
    "Chemistry (XI)": [
      {
        'id': 'basic',
        'title': "Basic Concepts",
        'tier': 'free',
        'topics': [
          'Mole concept applications',
          'Stoichiometry calculations',
          'Empirical formula determination',
          'Concentration terms',
        ],
      },
      {
        'id': 'atom',
        'title': "Structure of Atom",
        'tier': 'free',
        'topics': [
          'Atomic models development',
          'Quantum numbers',
          'Electronic configuration',
          'Atomic spectra',
        ],
      },
      {
        'id': 'periodic',
        'title': "Periodic Table",
        'tier': 'free',
        'topics': [
          'Periodic properties trends',
          's, p, d, f block elements',
          'Periodic table organization',
          'Chemical periodicity',
        ],
      },
      {
        'id': 'bonding',
        'title': "Chemical Bonding",
        'tier': 'free',
        'topics': [
          'Chemical bonding theories',
          'Molecular orbital theory',
          'Hybridization concepts',
          'Intermolecular forces',
        ],
      },
      {
        'id': 'states',
        'title': "States of Matter",
        'tier': 'free',
        'topics': [
          'Gas laws applications',
          'Liquid state properties',
          'Solid state characteristics',
          'State changes',
        ],
      },
      {
        'id': 'redox',
        'title': "Redox",
        'tier': 'free',
        'topics': [
          'Oxidation number concept',
          'Balancing redox reactions',
          'Electrochemical cells',
          'Redox titration',
        ],
      },
      {
        'id': 'organic',
        'title': "Organic Chemistry Fundamentals",
        'tier': 'free',
        'topics': [
          'IUPAC nomenclature',
          'Isomerism concepts',
          'Reaction mechanisms',
          'Functional group chemistry',
        ],
      },
      {
        'id': 'hydrocarbons',
        'title': "Hydrocarbons",
        'tier': 'free',
        'topics': [
          'Alkanes, alkenes, alkynes',
          'Aromatic hydrocarbons',
          'Petroleum refining',
          'Environmental aspects',
        ],
      },
    ],
    "Biology (XI)": [
      {
        'id': 'diversity',
        'title': "Diversity of Life",
        'tier': 'free',
        'topics': [
          'Classification systems',
          'Five kingdom details',
          'Virus and monera kingdoms',
          'Protist and fungi kingdoms',
        ],
      },
      {
        'id': 'plants',
        'title': "Plant Kingdom",
        'tier': 'free',
        'topics': [
          'Plant classification',
          'Major plant groups',
          'Plant life cycles',
          'Economic importance',
        ],
      },
      {
        'id': 'animals',
        'title': "Animal Kingdom",
        'tier': 'free',
        'topics': [
          'Animal phyla characteristics',
          'Vertebrate classification',
          'Comparative anatomy',
          'Evolutionary relationships',
        ],
      },
      {
        'id': 'cell',
        'title': "Cell Biology",
        'tier': 'free',
        'topics': [
          'Cell ultrastructure',
          'Biomembrane functions',
          'Cell division processes',
          'Cellular transport',
        ],
      },
      {
        'id': 'physiology',
        'title': "Plant Physiology",
        'tier': 'free',
        'topics': [
          'Plant water relations',
          'Mineral nutrition',
          'Photosynthesis mechanisms',
          'Respiration in plants',
        ],
      },
      {
        'id': 'biomolecules',
        'title': "Biomolecules",
        'tier': 'free',
        'topics': [
          'Carbohydrate chemistry',
          'Protein structure',
          'Lipid classification',
          'Nucleic acid functions',
        ],
      },
    ],
    "Physics (XII)": [
      {
        'id': 'charges',
        'title': "Electric Charges & Fields",
        'tier': 'free',
        'topics': [
          'Coulomb\'s law applications',
          'Electric field calculations',
          'Electric dipole moment',
          'Gauss\'s law applications',
        ],
      },
      {
        'id': 'magnetism',
        'title': "Magnetism",
        'tier': 'free',
        'topics': [
          'Magnetic materials classification',
          'Earth\'s magnetism',
          'Magnetic properties',
          'Electromagnetic applications',
        ],
      },
      {
        'id': 'waves',
        'title': "EM Waves",
        'tier': 'free',
        'topics': [
          'Electromagnetic spectrum',
          'Wave properties',
          'Propagation mechanisms',
          'Communication applications',
        ],
      },
      {
        'id': 'optics',
        'title': "Optics",
        'tier': 'free',
        'topics': [
          'Reflection through mirrors',
          'Refraction through lenses',
          'Optical instruments',
          'Wave optics phenomena',
        ],
      },
      {
        'id': 'dual',
        'title': "Dual Nature",
        'tier': 'free',
        'topics': [
          'Photoelectric effect',
          'Matter waves concept',
          'De Broglie hypothesis',
          'Wave-particle duality',
        ],
      },
      {
        'id': 'atoms',
        'title': "Atoms & Nuclei",
        'tier': 'free',
        'topics': [
          'Atomic structure models',
          'Nuclear properties',
          'Radioactive decay',
          'Nuclear reactions',
        ],
      },
      {
        'id': 'semiconductor',
        'title': "Semiconductor Electronics",
        'tier': 'free',
        'topics': [
          'Semiconductor physics',
          'Diode characteristics',
          'Transistor operation',
          'Digital electronics basics',
        ],
      },
    ],
    "Chemistry (XII)": [
      {
        'id': 'solutions',
        'title': "Solutions",
        'tier': 'free',
        'topics': [
          'Colligative properties',
          'Solution concentration',
          'Raoult\'s law applications',
          'Abnormal molecular masses',
        ],
      },
      {
        'id': 'electro',
        'title': "Electrochemistry",
        'tier': 'free',
        'topics': [
          'Electrochemical cells',
          'Conductance measurements',
          'Battery technology',
          'Corrosion science',
        ],
      },
      {
        'id': 'surface',
        'title': "Surface Chemistry",
        'tier': 'free',
        'topics': [
          'Adsorption phenomena',
          'Catalysis principles',
          'Colloid properties',
          'Surface chemistry applications',
        ],
      },
      {
        'id': 'kinetics',
        'title': "Chemical Kinetics",
        'tier': 'free',
        'topics': [
          'Reaction rate determination',
          'Rate law expressions',
          'Reaction mechanisms',
          'Catalysis effects',
        ],
      },
      {
        'id': 'coordination',
        'title': "Coordination Compounds",
        'tier': 'free',
        'topics': [
          'Werner\'s theory',
          'Isomerism in complexes',
          'Bonding theories',
          'Applications of coordination compounds',
        ],
      },
      {
        'id': 'carbonyl',
        'title': "Aldehydes/Ketones",
        'tier': 'free',
        'topics': [
          'Nomenclature and preparation',
          'Chemical properties',
          'Reaction mechanisms',
          'Industrial applications',
        ],
      },
      {
        'id': 'polymers',
        'title': "Polymers",
        'tier': 'free',
        'topics': [
          'Polymer classification',
          'Polymerization methods',
          'Natural and synthetic polymers',
          'Polymer applications',
        ],
      },
      {
        'id': 'biomolecules',
        'title': "Biomolecules",
        'tier': 'free',
        'topics': [
          'Carbohydrate chemistry',
          'Amino acids and proteins',
          'Enzyme functions',
          'Nucleic acid structure',
        ],
      },
    ],
    "Biology (XII)": [
      {
        'id': 'reproduction',
        'title': "Reproduction",
        'tier': 'free',
        'topics': [
          'Human reproduction system',
          'Reproductive health',
          'Birth control methods',
          'Menstrual cycle regulation',
        ],
      },
      {
        'id': 'genetics',
        'title': "Genetics",
        'tier': 'free',
        'topics': [
          'Mendelian inheritance',
          'Chromosomal theory',
          'Genetic disorders',
          'DNA fingerprinting',
        ],
      },
      {
        'id': 'evolution',
        'title': "Evolution",
        'tier': 'free',
        'topics': [
          'Origin of life theories',
          'Evolutionary patterns',
          'Human evolution',
          'Adaptive radiation',
        ],
      },
      {
        'id': 'physiology',
        'title': "Human Physiology",
        'tier': 'free',
        'topics': [
          'Digestive system details',
          'Circulatory system',
          'Nervous system functions',
          'Endocrine system regulation',
        ],
      },
      {
        'id': 'ecology',
        'title': "Ecology",
        'tier': 'free',
        'topics': [
          'Ecosystem structure',
          'Biodiversity conservation',
          'Environmental issues',
          'Wildlife protection',
        ],
      },
      {
        'id': 'biotech',
        'title': "Biotechnology",
        'tier': 'free',
        'topics': [
          'Genetic engineering',
          'Biotechnology applications',
          'DNA technology',
          'Ethical issues in biotechnology',
        ],
      },
    ],
    "Zoology (BSc)": [
      {
        'id': 'cell',
        'title': "Cell Biology",
        'tier': 'free',
        'topics': [
          'Cell structure and function',
          'Cellular organelles',
          'Cell division processes',
          'Cell signaling mechanisms',
        ],
      },
      {
        'id': 'classification',
        'title': "Animal Classification",
        'tier': 'vip',
        'topics': [
          'Invertebrate classification',
          'Vertebrate classification',
          'Comparative anatomy',
          'Evolutionary relationships',
        ],
      },
      {
        'id': 'evolution',
        'title': "Evolution",
        'tier': 'free',
        'topics': [
          'Natural selection mechanisms',
          'Speciation processes',
          'Evolutionary evidence',
          'Human evolution patterns',
        ],
      },
      {
        'id': 'physiology',
        'title': "Animal Physiology",
        'tier': 'vip',
        'topics': [
          'Organ system functions',
          'Homeostasis mechanisms',
          'Comparative physiology',
          'Adaptive features',
        ],
      },
    ],
    "Botany (BSc)": [
      {
        'id': 'plantcell',
        'title': "Plant Cell Biology",
        'tier': 'free',
        'topics': [
          'Plant cell structure',
          'Cellular processes',
          'Plant tissue types',
          'Cell wall composition',
        ],
      },
      {
        'id': 'anatomy',
        'title': "Plant Anatomy",
        'tier': 'vip',
        'topics': [
          'Plant tissue organization',
          'Root and stem anatomy',
          'Leaf structure',
          'Secondary growth processes',
        ],
      },
      {
        'id': 'taxonomy',
        'title': "Plant Taxonomy",
        'tier': 'free',
        'topics': [
          'Plant classification systems',
          'Identification keys',
          'Plant families',
          'Herbarium techniques',
        ],
      },
      {
        'id': 'physiology',
        'title': "Plant Physiology",
        'tier': 'vip',
        'topics': [
          'Photosynthesis mechanisms',
          'Plant hormone functions',
          'Mineral nutrition',
          'Plant growth regulators',
        ],
      },
    ],
    "Microbiology (BSc)": [
      {
        'id': 'microbes',
        'title': "Microbial Diversity",
        'tier': 'free',
        'topics': [
          'Bacterial classification',
          'Viral structure',
          'Fungal characteristics',
          'Microbial diversity',
        ],
      },
      {
        'id': 'bacteria',
        'title': "Bacterial Structure",
        'tier': 'vip',
        'topics': [
          'Bacterial cell structure',
          'Cell wall composition',
          'Capsule and flagella',
          'Genetic material organization',
        ],
      },
      {
        'id': 'genetics',
        'title': "Microbial Genetics",
        'tier': 'vip',
        'topics': [
          'Gene transfer mechanisms',
          'Mutation types',
          'Genetic engineering basics',
          'Plasmid technology',
        ],
      },
      {
        'id': 'industrial',
        'title': "Industrial Microbiology",
        'tier': 'free',
        'topics': [
          'Fermentation processes',
          'Industrial applications',
          'Quality control',
          'Production optimization',
        ],
      },
    ],
    "Genetics (BSc)": [
      {
        'id': 'mendelian',
        'title': "Mendelian Genetics",
        'tier': 'free',
        'topics': [
          'Mendel\'s experiments',
          'Inheritance patterns',
          'Genetic crosses',
          'Probability in genetics',
        ],
      },
      {
        'id': 'dna',
        'title': "DNA Replication",
        'tier': 'vip',
        'topics': [
          'DNA replication mechanisms',
          'Transcription process',
          'Translation machinery',
          'Genetic code properties',
        ],
      },
      {
        'id': 'molecular',
        'title': "Molecular Genetics",
        'tier': 'vip',
        'topics': [
          'Gene expression control',
          'Mutation mechanisms',
          'DNA repair systems',
          'Recombinant DNA technology',
        ],
      },
      {
        'id': 'biotech',
        'title': "Biotechnology Basics",
        'tier': 'free',
        'topics': [
          'Genetic engineering principles',
          'Cloning techniques',
          'PCR applications',
          'Biotechnology ethics',
        ],
      },
    ],
    "Ecology (BSc)": [
      {
        'id': 'ecosystems',
        'title': "Ecosystems",
        'tier': 'free',
        'topics': [
          'Energy flow patterns',
          'Nutrient cycling',
          'Community interactions',
          'Ecological succession',
        ],
      },
      {
        'id': 'conservation',
        'title': "Conservation Biology",
        'tier': 'vip',
        'topics': [
          'Conservation strategies',
          'Protected area management',
          'Species recovery programs',
          'Habitat restoration',
        ],
      },
      {
        'id': 'biodiversity',
        'title': "Biodiversity",
        'tier': 'free',
        'topics': [
          'Species richness measurement',
          'Biodiversity hotspots',
          'Threats to biodiversity',
          'Conservation genetics',
        ],
      },
    ],
    "Immunology (BSc)": [
      {
        'id': 'immune',
        'title': "Immune System",
        'tier': 'free',
        'topics': [
          'Innate immunity mechanisms',
          'Adaptive immunity development',
          'Immune cell functions',
          'Immune response regulation',
        ],
      },
      {
        'id': 'antibodies',
        'title': "Antibodies & Antigens",
        'tier': 'vip',
        'topics': [
          'Antibody structure',
          'Antigen recognition',
          'Immune complex formation',
          'Serological reactions',
        ],
      },
      {
        'id': 'vaccines',
        'title': "Vaccines",
        'tier': 'vip',
        'topics': [
          'Vaccine development',
          'Immunization schedules',
          'Vaccine types',
          'Herd immunity concept',
        ],
      },
    ],
    "Physical Chemistry (BSc)": [
      {
        'id': 'thermo',
        'title': "Thermodynamics",
        'tier': 'free',
        'topics': [
          'Laws of thermodynamics',
          'Thermodynamic functions',
          'Phase equilibria',
          'Chemical equilibrium',
        ],
      },
      {
        'id': 'quantum',
        'title': "Quantum Chemistry",
        'tier': 'vip',
        'topics': [
          'Wave functions',
          'Atomic structure',
          'Molecular orbital theory',
          'Spectroscopic principles',
        ],
      },
      {
        'id': 'kinetics',
        'title': "Chemical Kinetics",
        'tier': 'free',
        'topics': [
          'Reaction rate theories',
          'Catalysis mechanisms',
          'Reaction dynamics',
          'Kinetic measurements',
        ],
      },
      {
        'id': 'electro',
        'title': "Electrochemistry",
        'tier': 'vip',
        'topics': [
          'Electrode processes',
          'Battery systems',
          'Corrosion mechanisms',
          'Electroanalytical methods',
        ],
      },
    ],
    "Organic Chemistry (BSc)": [
      {
        'id': 'mechanisms',
        'title': "Reaction Mechanisms",
        'tier': 'free',
        'topics': [
          'Substitution reactions',
          'Addition reactions',
          'Elimination mechanisms',
          'Rearrangement reactions',
        ],
      },
      {
        'id': 'stereo',
        'title': "Stereochemistry",
        'tier': 'vip',
        'topics': [
          'Chirality concepts',
          'Optical isomerism',
          'Conformational analysis',
          'Stereoselective reactions',
        ],
      },
      {
        'id': 'synthesis',
        'title': "Organic Synthesis",
        'tier': 'vip',
        'topics': [
          'Retrosynthetic analysis',
          'Protecting groups',
          'Multi-step synthesis',
          'Natural product synthesis',
        ],
      },
      {
        'id': 'spectroscopy',
        'title': "Organic Spectroscopy",
        'tier': 'free',
        'topics': [
          'UV-Visible spectroscopy',
          'IR spectroscopy',
          'NMR techniques',
          'Mass spectrometry',
        ],
      },
    ],
    "Inorganic Chemistry (BSc)": [
      {
        'id': 'coordination',
        'title': "Coordination Compounds",
        'tier': 'free',
        'topics': [
          'Coordination numbers',
          'Isomerism in complexes',
          'Bonding theories',
          'Magnetic properties',
        ],
      },
      {
        'id': 'bonding',
        'title': "Chemical Bonding",
        'tier': 'vip',
        'topics': [
          'Valence bond theory',
          'Molecular orbital theory',
          'Crystal field theory',
          'Band theory of solids',
        ],
      },
      {
        'id': 'periodic',
        'title': "Periodic Trends",
        'tier': 'free',
        'topics': [
          'Periodic trends analysis',
          'Groupwise chemistry',
          'Chemical periodicity',
          'Anomalous behavior',
        ],
      },
      {
        'id': 'organometallic',
        'title': "Organometallic Chemistry",
        'tier': 'vip',
        'topics': [
          'Organometallic compounds',
          'Catalytic cycles',
          'Industrial applications',
          'Bioorganometallic chemistry',
        ],
      },
    ],
    "Analytical Chemistry (BSc)": [
      {
        'id': 'spectro',
        'title': "Spectroscopy",
        'tier': 'free',
        'topics': [
          'UV-Vis spectroscopy',
          'Atomic spectroscopy',
          'Molecular spectroscopy',
          'Spectroscopic analysis',
        ],
      },
      {
        'id': 'chromatography',
        'title': "Chromatography",
        'tier': 'vip',
        'topics': [
          'Gas chromatography',
          'Liquid chromatography',
          'Thin layer chromatography',
          'HPLC techniques',
        ],
      },
      {
        'id': 'titration',
        'title': "Titration Methods",
        'tier': 'free',
        'topics': [
          'Acid-base titrations',
          'Redox titrations',
          'Complexometric titrations',
          'Precipitation titrations',
        ],
      },
      {
        'id': 'analysis',
        'title': "Qualitative Analysis",
        'tier': 'vip',
        'topics': [
          'Cation analysis',
          'Anion analysis',
          'Systematic analysis',
          'Instrumental methods',
        ],
      },
    ],
    "Classical Mechanics (BSc)": [
      {
        'id': 'newton',
        'title': "Newtonian Mechanics",
        'tier': 'free',
        'topics': [
          'Newton\'s laws applications',
          'Conservation laws',
          'Collision theory',
          'Rigid body motion',
        ],
      },
      {
        'id': 'lagrangian',
        'title': "Lagrangian Mechanics",
        'tier': 'vip',
        'topics': [
          'Lagrangian formulation',
          'Hamiltonian mechanics',
          'Canonical transformations',
          'Action principles',
        ],
      },
      {
        'id': 'oscillations',
        'title': "Oscillations",
        'tier': 'free',
        'topics': [
          'Simple harmonic motion',
          'Damped oscillations',
          'Forced oscillations',
          'Coupled oscillators',
        ],
      },
      {
        'id': 'rigid',
        'title': "Rigid Body Dynamics",
        'tier': 'vip',
        'topics': [
          'Rotational dynamics',
          'Moment of inertia',
          'Angular momentum',
          'Gyroscopic motion',
        ],
      },
    ],
    "Electromagnetism (BSc)": [
      {
        'id': 'electro',
        'title': "Electrostatics",
        'tier': 'free',
        'topics': [
          'Coulomb\'s law',
          'Gauss\'s law applications',
          'Electric potential',
          'Capacitance concepts',
        ],
      },
      {
        'id': 'magnetism',
        'title': "Magnetism",
        'tier': 'vip',
        'topics': [
          'Magnetic materials',
          'Ampere\'s law',
          'Biot-Savart law',
          'Magnetic properties',
        ],
      },
      {
        'id': 'maxwell',
        'title': "Maxwell's Equations",
        'tier': 'vip',
        'topics': [
          'Maxwell\'s equations',
          'Electromagnetic waves',
          'Wave propagation',
          'Poynting vector',
        ],
      },
      {
        'id': 'waves',
        'title': "EM Waves",
        'tier': 'free',
        'topics': [
          'Wave equation solutions',
          'Polarization phenomena',
          'Reflection and refraction',
          'Wave guides',
        ],
      },
    ],




    
    "Quantum Mechanics (BSc)": [
      {
        'id': 'wave',
        'title': "Wave-Particle Duality",
        'tier': 'free',
        'topics': [
          'Photoelectric effect',
          'Compton effect',
          'de Broglie hypothesis',
          'Uncertainty principle',
        ],
      },
      {
        'id': 'schrodinger',
        'title': "Schrödinger Equation",
        'tier': 'vip',
        'topics': [
          'Wave function interpretation',
          'Operators in quantum mechanics',
          'Eigenvalue problems',
          'Time-dependent Schrödinger equation',
        ],
      },
      {
        'id': 'atoms',
        'title': "Hydrogen Atom",
        'tier': 'vip',
        'topics': [
          'Quantum numbers',
          'Wave functions',
          'Spectral series',
          'Fine structure',
        ],
      },
      {
        'id': 'spin',
        'title': "Spin and Angular Momentum",
        'tier': 'free',
        'topics': [
          'Spin operators',
          'Angular momentum algebra',
          'Addition of angular momenta',
          'Spin-orbit coupling',
        ],
      },
    ],
    "Solid State Physics (BSc)": [
      {
        'id': 'crystals',
        'title': "Crystal Structures",
        'tier': 'free',
        'topics': [
          'Crystal systems',
          'Miller indices',
          'Crystal defects',
          'X-ray diffraction',
        ],
      },
      {
        'id': 'semiconductors',
        'title': "Semiconductors",
        'tier': 'vip',
        'topics': [
          'Band theory',
          'Semiconductor types',
          'Diode characteristics',
          'Transistor operation',
        ],
      },
      {
        'id': 'superconductivity',
        'title': "Superconductivity",
        'tier': 'vip',
        'topics': [
          'Meissner effect',
          'BCS theory',
          'Type I and II superconductors',
          'High-temperature superconductors',
        ],
      },
      {
        'id': 'magnetism',
        'title': "Magnetic Properties",
        'tier': 'free',
        'topics': [
          'Diamagnetism',
          'Paramagnetism',
          'Ferromagnetism',
          'Magnetic domains',
        ],
      },
    ],
    "Optics (BSc)": [
      {
        'id': 'geometrical',
        'title': "Geometrical Optics",
        'tier': 'free',
        'topics': [
          'Ray approximation',
          'Mirror equations',
          'Lens formulas',
          'Optical instruments',
        ],
      },
      {
        'id': 'wave',
        'title': "Wave Optics",
        'tier': 'vip',
        'topics': [
          'Huygens principle',
          'Interference phenomena',
          'Diffraction theory',
          'Polarization effects',
        ],
      },
      {
        'id': 'interference',
        'title': "Interference",
        'tier': 'free',
        'topics': [
          'Young\'s experiment',
          'Michelson interferometer',
          'Fabry-Perot interferometer',
          'Interference applications',
        ],
      },
      {
        'id': 'lasers',
        'title': "Lasers",
        'tier': 'vip',
        'topics': [
          'Laser principles',
          'Population inversion',
          'Optical resonators',
          'Laser types and applications',
        ],
      },
    ],
    "Thermodynamics (BSc)": [
      {
        'id': 'laws',
        'title': "Laws of Thermodynamics",
        'tier': 'free',
        'topics': [
          'Zeroth law applications',
          'First law formulations',
          'Second law statements',
          'Third law implications',
        ],
      },
      {
        'id': 'entropy',
        'title': "Entropy",
        'tier': 'vip',
        'topics': [
          'Entropy calculations',
          'Thermodynamic potentials',
          'Maxwell relations',
          'Phase transitions',
        ],
      },
      {
        'id': 'kinetic',
        'title': "Kinetic Theory",
        'tier': 'free',
        'topics': [
          'Kinetic theory derivations',
          'Distribution functions',
          'Transport phenomena',
          'Real gas behavior',
        ],
      },
      {
        'id': 'statistical',
        'title': "Statistical Mechanics",
        'tier': 'vip',
        'topics': [
          'Ensemble theory',
          'Partition functions',
          'Quantum statistics',
          'Applications to systems',
        ],
      },
    ],
    "Molecular Biology (Biotech)": [
      {
        'id': 'dna',
        'title': "DNA Structure",
        'tier': 'free',
        'topics': [
          'DNA double helix',
          'Base pairing rules',
          'DNA topology',
          'Chromatin structure',
        ],
      },
      {
        'id': 'replication',
        'title': "DNA Replication",
        'tier': 'vip',
        'topics': [
          'Enzymes involved',
          'Replication forks',
          'Proofreading mechanisms',
          'DNA repair systems',
        ],
      },
      {
        'id': 'transcription',
        'title': "Transcription",
        'tier': 'free',
        'topics': [
          'RNA polymerase',
          'Transcription factors',
          'RNA processing',
          'Gene regulation',
        ],
      },
      {
        'id': 'translation',
        'title': "Translation",
        'tier': 'vip',
        'topics': [
          'Ribosome structure',
          'Genetic code',
          'Protein synthesis',
          'Post-translational modifications',
        ],
      },
    ],
    "Genetic Engineering (Biotech)": [
      {
        'id': 'recombinant',
        'title': "Recombinant DNA Technology",
        'tier': 'free',
        'topics': [
          'Restriction enzymes',
          'DNA ligation',
          'Vector systems',
          'Transformation methods',
        ],
      },
      {
        'id': 'cloning',
        'title': "Gene Cloning",
        'tier': 'vip',
        'topics': [
          'Plasmid vectors',
          'Expression systems',
          'Genomic libraries',
          'Screening methods',
        ],
      },
      {
        'id': 'pcr',
        'title': "PCR Techniques",
        'tier': 'vip',
        'topics': [
          'PCR principles',
          'Real-time PCR',
          'Mutation detection',
          'DNA sequencing',
        ],
      },
      {
        'id': 'crispr',
        'title': "CRISPR Technology",
        'tier': 'free',
        'topics': [
          'CRISPR mechanism',
          'Gene editing applications',
          'Therapeutic uses',
          'Ethical considerations',
        ],
      },
    ],
    "Microbial Technology (Biotech)": [
      {
        'id': 'fermentation',
        'title': "Industrial Fermentation",
        'tier': 'free',
        'topics': [
          'Batch fermentation',
          'Continuous fermentation',
          'Fed-batch processes',
          'Process optimization',
        ],
      },
      {
        'id': 'bioreactors',
        'title': "Bioreactors",
        'tier': 'vip',
        'topics': [
          'Bioreactor design',
          'Scale-up principles',
          'Process control',
          'Sterilization methods',
        ],
      },
      {
        'id': 'enzymes',
        'title': "Enzyme Technology",
        'tier': 'vip',
        'topics': [
          'Enzyme kinetics',
          'Immobilization techniques',
          'Industrial applications',
          'Enzyme engineering',
        ],
      },
    ],
    "Bioinformatics (Biotech)": [
      {
        'id': 'sequence',
        'title': "Sequence Alignment",
        'tier': 'free',
        'topics': [
          'Pairwise alignment',
          'Multiple sequence alignment',
          'Alignment algorithms',
          'Scoring matrices',
        ],
      },
      {
        'id': 'databases',
        'title': "Genomic Databases",
        'tier': 'vip',
        'topics': [
          'GenBank resources',
          'Protein databases',
          'Data mining',
          'Database searching',
        ],
      },
      {
        'id': 'structure',
        'title': "Protein Structure Prediction",
        'tier': 'vip',
        'topics': [
          'Secondary structure',
          'Tertiary structure',
          'Homology modeling',
          'Structure prediction',
        ],
      },
    ],
    "Immunology (Biotech)": [
      {
        'id': 'immune',
        'title': "Immune System",
        'tier': 'free',
        'topics': [
          'Immune cell development',
          'Immune organ functions',
          'Innate immunity',
          'Adaptive immunity',
        ],
      },
      {
        'id': 'antigens',
        'title': "Antigen-Antibody Reactions",
        'tier': 'vip',
        'topics': [
          'Epitope mapping',
          'Antibody production',
          'Immunoassays',
          'Diagnostic applications',
        ],
      },
      {
        'id': 'vaccines',
        'title': "Vaccine Development",
        'tier': 'vip',
        'topics': [
          'Vaccine design',
          'Clinical trials',
          'Vaccine production',
          'New vaccine development',
        ],
      },
    ],
    "Environmental Science (BSc)": [
      {
        'id': 'pollution',
        'title': "Pollution",
        'tier': 'free',
        'topics': [
          'Air pollution sources',
          'Water pollution types',
          'Soil contamination',
          'Pollution control methods',
        ],
      },
      {
        'id': 'ecology',
        'title': "Ecology",
        'tier': 'free',
        'topics': [
          'Population ecology',
          'Community ecology',
          'Ecosystem dynamics',
          'Conservation ecology',
        ],
      },
      {
        'id': 'laws',
        'title': "Environmental Laws",
        'tier': 'vip',
        'topics': [
          'Environmental legislation',
          'International agreements',
          'Policy implementation',
          'Regulatory frameworks',
        ],
      },
      {
        'id': 'soil',
        'title': "Soil Science",
        'tier': 'free',
        'topics': [
          'Soil formation',
          'Soil classification',
          'Soil conservation',
          'Land use management',
        ],
      },
      {
        'id': 'water',
        'title': "Water Management",
        'tier': 'vip',
        'topics': [
          'Water treatment',
          'Water quality assessment',
          'Wastewater management',
          'Water resource planning',
        ],
      },
      {
        'id': 'climate',
        'title': "Climate Change",
        'tier': 'vip',
        'topics': [
          'Climate change science',
          'Mitigation strategies',
          'Adaptation measures',
          'Climate policy',
        ],
      },
    ],
    "Advanced Genetics (MSc)": [
      {
        'id': 'mapping',
        'title': "Gene Mapping",
        'tier': 'vip',
        'topics': [
          'Genetic mapping techniques',
          'Linkage analysis',
          'Physical mapping',
          'Genome sequencing',
        ],
      },
      {
        'id': 'disorders',
        'title': "Genetic Disorders",
        'tier': 'vip',
        'topics': [
          'Chromosomal abnormalities',
          'Single gene disorders',
          'Multifactorial disorders',
          'Genetic counseling',
        ],
      },
      {
        'id': 'population',
        'title': "Population Genetics",
        'tier': 'vip',
        'topics': [
          'Hardy-Weinberg principle',
          'Genetic drift',
          'Gene flow',
          'Natural selection models',
        ],
      },
    ],
    "Molecular Cell Biology (MSc)": [
      {
        'id': 'signaling',
        'title': "Cell Signaling",
        'tier': 'vip',
        'topics': [
          'Signal transduction pathways',
          'Receptor mechanisms',
          'Second messengers',
          'Cellular responses',
        ],
      },
      {
        'id': 'division',
        'title': "Cell Division Control",
        'tier': 'vip',
        'topics': [
          'Cell cycle regulation',
          'Checkpoint controls',
          'Cancer cell biology',
          'Cell death mechanisms',
        ],
      },
      {
        'id': 'cancer',
        'title': "Cancer Biology",
        'tier': 'vip',
        'topics': [
          'Oncogenes',
          'Tumor suppressors',
          'Cancer genetics',
          'Therapeutic approaches',
        ],
      },
    ],
    "Biophysics (MSc)": [
      {
        'id': 'structure',
        'title': "Biomolecular Structure",
        'tier': 'vip',
        'topics': [
          'Protein structure determination',
          'Nucleic acid structure',
          'Membrane structure',
          'Structural biology techniques',
        ],
      },
      {
        'id': 'dynamics',
        'title': "Molecular Dynamics",
        'tier': 'vip',
        'topics': [
          'Molecular simulations',
          'Energy minimization',
          'Conformational analysis',
          'Dynamic processes',
        ],
      },
      {
        'id': 'spectroscopy',
        'title': "Biological Spectroscopy",
        'tier': 'vip',
        'topics': [
          'Spectroscopic methods',
          'Calorimetric techniques',
          'Microscopy advances',
          'Single molecule techniques',
        ],
      },
    ],
    "Developmental Biology (MSc)": [
      {
        'id': 'embryo',
        'title': "Embryonic Development",
        'tier': 'vip',
        'topics': [
          'Gametogenesis',
          'Fertilization',
          'Early development',
          'Embryonic patterning',
        ],
      },
      {
        'id': 'stem',
        'title': "Stem Cell Biology",
        'tier': 'vip',
        'topics': [
          'Stem cell types',
          'Differentiation pathways',
          'Regenerative medicine',
          'Therapeutic applications',
        ],
      },
      {
        'id': 'organ',
        'title': "Organogenesis",
        'tier': 'vip',
        'topics': [
          'Organ formation',
          'Tissue interactions',
          'Developmental genetics',
          'Evolutionary developmental biology',
        ],
      },
    ],
    "Advanced Organic Synthesis (MSc)": [
      {
        'id': 'synthesis',
        'title': "Organic Synthesis",
        'tier': 'vip',
        'topics': [
          'Retrosynthetic analysis',
          'Synthetic strategy design',
          'Complex molecule synthesis',
          'Natural product synthesis',
        ],
      },
      {
        'id': 'mechanisms',
        'title': "Advanced Mechanisms",
        'tier': 'vip',
        'topics': [
          'Pericyclic reactions',
          'Photochemical reactions',
          'Radical reactions',
          'Organometallic reactions',
        ],
      },
      {
        'id': 'catalysis',
        'title': "Asymmetric Catalysis",
        'tier': 'vip',
        'topics': [
          'Chiral catalysts',
          'Enantioselective synthesis',
          'Diastereoselective reactions',
          'Asymmetric methodologies',
        ],
      },
    ],
    "Spectroscopy (MSc)": [
      {
        'id': 'nmr',
        'title': "NMR Spectroscopy",
        'tier': 'vip',
        'topics': [
          '1D and 2D NMR',
          'Structural elucidation',
          'Dynamic NMR',
          'Solid state NMR',
        ],
      },
      {
        'id': 'mass',
        'title': "Mass Spectrometry",
        'tier': 'vip',
        'topics': [
          'Ionization techniques',
          'Mass analyzers',
          'Tandem MS',
          'Proteomic applications',
        ],
      },
      {
        'id': 'xray',
        'title': "X-ray Crystallography",
        'tier': 'vip',
        'topics': [
          'Crystal growth',
          'Diffraction theory',
          'Structure solution',
          'Refinement techniques',
        ],
      },
    ],
    "Organometallic Chemistry (MSc)": [
      {
        'id': 'catalysis',
        'title': "Organometallic Catalysis",
        'tier': 'vip',
        'topics': [
          'Homogeneous catalysis',
          'Catalytic cycles',
          'Industrial processes',
          'Green chemistry applications',
        ],
      },
      {
        'id': 'clusters',
        'title': "Metal Clusters",
        'tier': 'vip',
        'topics': [
          'Metal cluster synthesis',
          'Bonding in clusters',
          'Catalytic properties',
          'Applications in materials',
        ],
      },
      {
        'id': 'bonding',
        'title': "Metal-Carbon Bonding",
        'tier': 'vip',
        'topics': [
          'Metal-carbon bonds',
          'Bonding theories',
          'Reactivity patterns',
          'Synthetic applications',
        ],
      },
    ],
    "Nanochemistry (MSc)": [
      {
        'id': 'nanoparticles',
        'title': "Nanoparticles",
        'tier': 'vip',
        'topics': [
          'Nanoparticle synthesis',
          'Core-shell structures',
          'Functionalization methods',
          'Characterization techniques',
        ],
      },
      {
        'id': 'synthesis',
        'title': "Nanomaterial Synthesis",
        'tier': 'vip',
        'topics': [
          'Bottom-up approaches',
          'Top-down methods',
          'Self-assembly processes',
          'Template synthesis',
        ],
      },
      {
        'id': 'applications',
        'title': "Nanotechnology Applications",
        'tier': 'vip',
        'topics': [
          'Characterization methods',
          'Size determination',
          'Surface analysis',
          'Structural characterization',
        ],
      },
    ],
    "Advanced Quantum Mechanics (MSc)": [
      {
        'id': 'relativistic',
        'title': "Relativistic Quantum Mechanics",
        'tier': 'vip',
        'topics': [
          'Dirac equation',
          'Relativistic effects',
          'Quantum electrodynamics',
          'Field quantization',
        ],
      },
      {
        'id': 'field',
        'title': "Quantum Field Theory",
        'tier': 'vip',
        'topics': [
          'Canonical quantization',
          'Path integral formulation',
          'Gauge theories',
          'Renormalization',
        ],
      },
      {
        'id': 'entanglement',
        'title': "Quantum Entanglement",
        'tier': 'vip',
        'topics': [
          'Bell\'s theorem',
          'Quantum correlations',
          'Quantum information',
          'Quantum computing basics',
        ],
      },
    ],
    "Particle Physics (MSc)": [
      {
        'id': 'standard',
        'title': "Standard Model",
        'tier': 'vip',
        'topics': [
          'Fundamental particles',
          'Force carriers',
          'Symmetry principles',
          'Standard Model predictions',
        ],
      },
      {
        'id': 'quarks',
        'title': "Quarks and Leptons",
        'tier': 'vip',
        'topics': [
          'Quark properties',
          'Lepton characteristics',
          'Generation patterns',
          'Mixing phenomena',
        ],
      },
      {
        'id': 'detectors',
        'title': "Particle Detectors",
        'tier': 'vip',
        'topics': [
          'Detection principles',
          'Accelerator technology',
          'Data analysis',
          'Experimental techniques',
        ],
      },
    ],
    "Nuclear Physics (MSc)": [
      {
        'id': 'structure',
        'title': "Nuclear Structure",
        'tier': 'vip',
        'topics': [
          'Nuclear models',
          'Shell model',
          'Collective model',
          'Nuclear structure calculations',
        ],
      },
      {
        'id': 'reactions',
        'title': "Nuclear Reactions",
        'tier': 'vip',
        'topics': [
          'Reaction mechanisms',
          'Cross-section measurements',
          'Nuclear astrophysics',
          'Synthesis processes',
        ],
      },
      {
        'id': 'decay',
        'title': "Radioactive Decay",
        'tier': 'vip',
        'topics': [
          'Decay modes',
          'Half-life measurements',
          'Dating methods',
          'Medical applications',
        ],
      },
    ],
    "Astrophysics (MSc)": [
      {
        'id': 'stars',
        'title': "Stellar Evolution",
        'tier': 'vip',
        'topics': [
          'Stellar formation',
          'Main sequence evolution',
          'Stellar death processes',
          'Supernova mechanisms',
        ],
      },
      {
        'id': 'cosmology',
        'title': "Cosmology",
        'tier': 'vip',
        'topics': [
          'Cosmological models',
          'Dark matter evidence',
          'Dark energy properties',
          'Cosmic microwave background',
        ],
      },
      {
        'id': 'blackholes',
        'title': "Black Holes",
        'tier': 'vip',
        'topics': [
          'Event horizon',
          'Hawking radiation',
          'Accretion disks',
          'Gravitational waves',
        ],
      },
    ],
    "Condensed Matter (MSc)": [
      {
        'id': 'quantum',
        'title': "Quantum Materials",
        'tier': 'vip',
        'topics': [
          'Topological insulators',
          'Quantum Hall effect',
          'Superconducting materials',
          'Novel quantum states',
        ],
      },
      {
        'id': 'superconductivity',
        'title': "Superconductivity",
        'tier': 'vip',
        'topics': [
          'BCS theory details',
          'High-Tc mechanisms',
          'Superconducting applications',
          'Josephson junctions',
        ],
      },
      {
        'id': 'nanophysics',
        'title': "Nanophysics",
        'tier': 'vip',
        'topics': [
          'Quantum dots',
          'Nanowires',
          '2D materials',
          'Nanoscale phenomena',
        ],
      },
    ],
    "Recombinant DNA Technology (MSc)": [
      {
        'id': 'vectors',
        'title': "Advanced Vector Design",
        'tier': 'vip',
        'topics': [
          'Vector design principles',
          'Expression optimization',
          'Synthetic biology',
          'Metabolic engineering',
        ],
      },
      {
        'id': 'expression',
        'title': "Gene Expression Systems",
        'tier': 'vip',
        'topics': [
          'Promoter systems',
          'Inducible expression',
          'Secretion systems',
          'Protein targeting',
        ],
      },
      {
        'id': 'editing',
        'title': "Genome Editing",
        'tier': 'vip',
        'topics': [
          'Zinc finger nucleases',
          'TALEN technology',
          'CRISPR systems',
          'Therapeutic genome editing',
        ],
      },
    ],
    "Advanced Immunology (MSc)": [
      {
        'id': 'immunity',
        'title': "Advanced Immunity",
        'tier': 'vip',
        'topics': [
          'Immune cell development',
          'Tolerance mechanisms',
          'Memory responses',
          'Vaccine immunology',
        ],
      },
      {
        'id': 'autoimmune',
        'title': "Autoimmune Diseases",
        'tier': 'vip',
        'topics': [
          'Autoimmune pathogenesis',
          'Immunodeficiency diseases',
          'Hypersensitivity reactions',
          'Transplant immunology',
        ],
      },
      {
        'id': 'immunotherapy',
        'title': "Immunotherapy",
        'tier': 'vip',
        'topics': [
          'Cancer immunology',
          'Immunotherapy approaches',
          'Checkpoint inhibitors',
          'CAR-T cell therapy',
        ],
      },
    ],
    "Proteomics (MSc)": [
      {
        'id': 'proteome',
        'title': "Proteome Analysis",
        'tier': 'vip',
        'topics': [
          'Protein separation',
          'Mass spectrometry',
          'Quantitative proteomics',
          'Post-translational modifications',
        ],
      },
      {
        'id': 'massspec',
        'title': "Mass Spectrometry",
        'tier': 'vip',
        'topics': [
          'Instrumentation principles',
          'Data acquisition',
          'Spectral analysis',
          'Quantification methods',
        ],
      },
      {
        'id': 'interactions',
        'title': "Protein Interactions",
        'tier': 'vip',
        'topics': [
          'Yeast two-hybrid',
          'Co-immunoprecipitation',
          'Protein arrays',
          'Network analysis',
        ],
      },
    ],
    "Drug Design (MSc)": [
      {
        'id': 'design',
        'title': "Drug Design Principles",
        'tier': 'vip',
        'topics': [
          'Target identification',
          'Lead discovery',
          'Structure-activity relationships',
          'Optimization strategies',
        ],
      },
      {
        'id': 'targets',
        'title': "Drug Targets",
        'tier': 'vip',
        'topics': [
          'Receptor biology',
          'Enzyme inhibitors',
          'Ion channel modulators',
          'GPCR targeting',
        ],
      },
      {
        'id': 'delivery',
        'title': "Drug Delivery Systems",
        'tier': 'vip',
        'topics': [
          'ADME properties',
          'Toxicity assessment',
          'Formulation development',
          'Clinical trial design',
        ],
      },
    ],
    "Bioprocess Engineering (MSc)": [
      {
        'id': 'scaleup',
        'title': "Process Scale-up",
        'tier': 'vip',
        'topics': [
          'Scale-up criteria',
          'Process economics',
          'Regulatory compliance',
          'Technology transfer',
        ],
      },
      {
        'id': 'optimization',
        'title': "Process Optimization",
        'tier': 'vip',
        'topics': [
          'Process modeling',
          'Parameter optimization',
          'Quality by design',
          'Process analytical technology',
        ],
      },
      {
        'id': 'purification',
        'title': "Protein Purification",
        'tier': 'vip',
        'topics': [
          'Chromatography methods',
          'Filtration techniques',
          'Crystallization processes',
          'Formulation development',
        ],
      },
    ],
    "NEET Preparation": [
      {
        'id': 'biology',
        'title': "NEET Biology",
        'tier': 'vip',
        'topics': [
          'Human physiology systems',
          'Plant physiology mechanisms',
          'Reproduction biology',
          'Genetics and evolution concepts',
        ],
      },
      {
        'id': 'physics',
        'title': "NEET Physics",
        'tier': 'vip',
        'topics': [
          'Human physiology details',
          'Digestive system',
          'Respiratory system',
          'Circulatory system',
          'Excretory system',
          'Nervous system',
          'Endocrine system',
        ],
      },
      {
        'id': 'chemistry',
        'title': "NEET Chemistry",
        'tier': 'vip',
        'topics': [
          'Photosynthesis',
          'Respiration in plants',
          'Plant growth regulators',
          'Mineral nutrition',
          'Transport in plants',
        ],
      },
    ],
    "JEE Main Preparation": [
      {
        'id': 'physics',
        'title': "JEE Main Physics",
        'tier': 'vip',
        'topics': [
          'Mechanics problems',
          'Electromagnetism concepts',
          'Optics applications',
          'Modern physics topics',
        ],
      },
      {
        'id': 'chemistry',
        'title': "JEE Main Chemistry",
        'tier': 'vip',
        'topics': [
          'Kinematics problems',
          'Dynamics applications',
          'Work-energy theorem',
          'Rotational motion',
          'Gravitation calculations',
        ],
      },
      {
        'id': 'math',
        'title': "JEE Main Mathematics",
        'tier': 'vip',
        'topics': [
          'Electrostatics problems',
          'Current electricity',
          'Magnetic effects',
          'EM induction',
          'AC circuits',
        ],
      },
    ],
    "JEE Advanced Preparation": [
      {
        'id': 'physics',
        'title': "JEE Advanced Physics",
        'tier': 'vip',
        'topics': [
          'Advanced kinematics',
          'Rigid body dynamics',
          'Fluid mechanics',
          'Thermal physics advanced',
        ],
      },
      {
        'id': 'chemistry',
        'title': "JEE Advanced Chemistry",
        'tier': 'vip',
        'topics': [
          'Electrostatics advanced',
          'Magnetostatics complex',
          'EM theory applications',
          'Wave optics advanced',
        ],
      },
    ],
    "Science Olympiads": [
      {
        'id': 'junior',
        'title': "Junior Olympiad (Class 1-5)",
        'tier': 'free',
        'topics': [
          'Basic science concepts',
          'Logical reasoning',
          'Observation skills',
          'Scientific thinking',
        ],
      },
      {
        'id': 'senior',
        'title': "Senior Olympiad (Class 6-10)",
        'tier': 'free',
        'topics': [
          'Physics fundamentals',
          'Chemistry basics',
          'Biology principles',
          'Earth science concepts',
        ],
      },
      {
        'id': 'advanced',
        'title': "Advanced Olympiad (Class 11-12)",
        'tier': 'vip',
        'topics': [
          'Advanced problem solving',
          'Theoretical concepts',
          'Experimental design',
          'Scientific methodology',
        ],
      },
    ],
  };

}
